#!/bin/bash
#Killers
if [ "$(id -u)" != "0" ]; then
 echo 'You must run this script as root'
 exit
fi

if [ "$AUTO" != "true" ]; then
	echo 'Please use demanager, instead of this script'
	exit
fi
#end of killers

DePath=$(demanager -loc)

rm -rf /tmp/desshRecreate.d
mkdir -p /tmp/desshRecreate.d/installation
pwd > /tmp/desshRecreate.d/loc
cd /tmp/desshRecreate.d/installation

cp $DePath/plugins/recreate/files/dessh.tar.gz ./
tar xzf dessh.tar.gz

#Recreating
mv ver $DePath/plugins/files/dessh/version

mv desshupdate $DePath/plugins/update/dessh.update
mv desshrecreate $DePath/plugins/recreate/scripts/dessh.recreate

echo '#==== DeSSH ====' >> /etc/bashrc.aliases
cat aliases >> /etc/bashrc.aliases
echo '################' >> /etc/bashrc.aliases

cd $(cat /tmp/desshRecreate.d/loc)
rm -rf /tmp/desshRecreate.d
echo "DeSSH: Recreating done."
